config/routes.rb
require "subscribm/constraints/subdomain_required"

Subscribm::Engine.routes.draw do

	constraints(Subscribm::Constraints::SubdomainRequired) do
		scope :module => "account" do
			root :to => "dashboard#index", :as => :account_root
			get "/sign_in", :to => "sessions#new"
			post "/sign_in", :to => "sessions#create", :as => :sessions
			get "/sign_up", :to => "users#new", :as => :user_sign_up
			post "/sign_up", :to => "users#create", :as => :do_user_sign_up
		end
	end
	
	root "dashboard#index"
	
	get "/sign_up", :to => "accounts#new", :as => :sign_up
	post "/accounts", :to => "accounts#create", :as => :accounts
	
end

app/models/subscribm/account.rb
EXCLUDED_SUBDOMAINS = %w(admin)

module Subscribm
  class Account < ActiveRecord::Base
	has_many :members, :class_name => "Subscribm::Member"
	has_many :users, :through => :members
	validates_exclusion_of :subdomain, :in => EXCLUDED_SUBDOMAINS,
		:message => "is not allowed. Please choose another subdomain."
	validates_format_of :subdomain, :with => /\A[\w\-]+\Z/i,
		:message => "is not allowed. Please choose another subdomain."
	validates :subdomain, :presence => true, :uniqueness => true
	belongs_to :owner, :class_name => "Subscribm::User"
	accepts_nested_attributes_for :owner
	
	before_validation do
		self.subdomain = subdomain.to_s.downcase
	end
	
	def self.create_with_owner(params={})
		account = new(params)
		if account.save
			account.users << account.owner
		end
		account
	end
	
	def create_schema
		Apartment::Tenant.create(subdomain)
	end
	
  end
end

app/models/subscribm/member.rb
module Subscribm
  class Member < ActiveRecord::Base
	belongs_to :account, :class_name => "Subscribm::Account"
	belongs_to :user, :class_name => "Subscribm::User"
  end
end

app/models/subscribm/user.rb
module Subscribm
  class User < ActiveRecord::Base
	has_secure_password
  end
end

app/controllers/subscribm/account/dashboard_controller.rb
require_dependency "subscribm/application_controller"

module Subscribm
  class Account::DashboardController < ApplicationController
	before_filter :authenticate_user!
	
  end
end

app/controllers/subscribm/account/sessions_controller.rb
require_dependency "subscribm/application_controller"

module Subscribm
  class Account::SessionsController < Subscribm::ApplicationController
	def new
		@user = User.new
	end
	def create
		if env["warden"].authenticate(:scope => :user)
			flash[:notice] = "You are now signed in."
			redirect_to root_path
		else
			@user = User.new
			flash[:error] = "Invalid email or password."
			render :action => "new"
		end
	end
  end
end

app/controllers/subscribm/account/users_controller.rb
require_dependency "subscribm/application_controller"

module Subscribm
  class Account::UsersController < ApplicationController
	def new 
		@user = Subscribm::User.new
	end
	def create
		account = Subscribm::Account.find_by!(:subdomain => request.subdomain)
		user = account.users.create(user_params)
		force_authentication!(user)
		flash[:success] = "You have signed up successfully."
		redirect_to root_path
	end
	private
		def user_params
			params.require(:user).permit(:email, :password, :password_confirmation)
		end
  end
end

app/controllers/subscribm/accounts_controller.rb
require_dependency "subscribm/application_controller"

module Subscribm
  class AccountsController < ApplicationController
  
	def new
		@account = Subscribm::Account.new
		@account.build_owner
	end
	
	def create
		@account = Subscribm::Account.create_with_owner(account_params)
		
		if @account.valid?
			force_authentication!(@account.owner)
			flash[:success] = "Your account has been successfully created."
			redirect_to subscribm.root_url(:subdomain => @account.subdomain)
		else
			flash[:error] = "Sorry, your account could not be created."
			render :new
		end
	end
	
	private
	def account_params
		params.require(:account).permit(:name, :subdomain,
		{:owner_attributes => [
			:email, :password, :password_confirmation
		]})
	end
  end
end

app/controllers/subscribm/application_controller.rb
module Subscribm
  class ApplicationController < ::ApplicationController
  
	
	
	
  end
end

app/controllers/subscribm/dashboard_controller.rb
module Subscribm
  class DashboardController < ApplicationController
	
	
  end
end

app/helpers/subscribm/account/dashboard_helper.rb
module Subscribm
  module Account::DashboardHelper
  end
end

app/helpers/subscribm/account/sessions_helper.rb
module Subscribm
  module Account::SessionsHelper
  end
end

app/helpers/subscribm/account/users_helper.rb
module Subscribm
  module Account::UsersHelper
  end
end

app/helpers/subscribm/accounts_helper.rb
module Subscribm
  module AccountsHelper
  end
end

app/helpers/subscribm/application_helper.rb
module Subscribm
  module ApplicationHelper
  end
end

app/helpers/subscribm/dashboard_helper.rb
module Subscribm
  module DashboardHelper
  end
end

app/views/layouts/subscribm/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscribm</title>
  <%= stylesheet_link_tag    "subscribm/application", media: "all" %>
  <%= javascript_include_tag "subscribm/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% flash.each do |k,v| %>
	<div class='flash <%= k %>'><%= v %></div>
 <% end %>
 <%= render "subscribm/shared/login" %>
<%= yield %>

</body>
</html>

app/views/subscribm/account/dashboard/index.html.erb
Your account's dashboard.  Coming soon.

app/views/subscribm/account/users/_form.html.erb
<p>
		<%= user.label :email %><br>
		<%= user.email_field :email %>
	</p>
	<p>
		<%= user.label :password %><br>
		<%= user.password_field :password%>
	</p>
	<p>
		<%= user.label :password_confirmation %><br>
		<%= user.password_field :password_confirmation %>
	</p>

app/views/subscribm/account/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@user, :url => do_user_sign_up_url) do |user| %>
	<%= render "subscribm/account/users/form", :user => user %>
	<%= user.submit "Sign up" %>
<% end %>

app/views/subscribm/accounts/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@account) do |account| %>
	<%= account.error_messages %>
<p>
<%= account.label :name %><br>
<%= account.text_field :name %>
</p>
<p>
	<%= account.label :subdomain %><br>
	<%= account.text_field :subdomain %>
</p>
<%= account.fields_for :owner do |owner| %>
	<%= render "subscribm/account/users/form", :user => owner %>
<% end %>
<%= account.submit %>
<% end %>

app/views/subscribm/dashboard/index.html.erb
<%= link_to "Account Sign Up", sign_up_path %>

app/views/subscribm/shared/_login.html.erb
<% if user_signed_in? %>
	Signed in as <%= current_user.email %>
<% else %>
	<%= link_to "Sign in", subscribm.sign_in_path %>
<% end %>